import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomBytes, createHash } from 'node:crypto';
import { build } from 'esbuild';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { chromium } from 'playwright-core';
import { BrowserRecovery, recoveryNavigation } from '../src/agent/browser-recovery.mjs';
import { authorizationReturn } from '../src/shared/authorization-navigation.mjs';
import { consentPage } from '../src/relay/consent-page.mjs';
import { startController } from '../src/agent/main.mjs';
import { Store } from '../src/agent/store.mjs';

const secret = () => randomBytes(32).toString('hex');
const decode = async (response, expected = 200) => { assert.equal(response.status, expected, await response.clone().text()); return response.json(); };
const until = async fn => { const until = Date.now() + 12000; while (Date.now() < until) { if (await fn()) return; await new Promise(r => setTimeout(r, 50)); } throw Error('Condition timed out'); };

test('limited recovery nonce is one-use, browser-bound, expiring and bound to current local permissions', () => {
  let now = 1000; const recovery = new BrowserRecovery({ now: () => now });
  const value = recovery.issue('original');
  assert.throws(() => recovery.consume(value, '', 'original'), /本机页面/);
  assert.throws(() => recovery.consume(value, `c2l_recovery=${value}; c2l_recovery=${value}`, 'original'));
  recovery.consume(value, `c2l_recovery=${value}`, 'original');
  assert.throws(() => recovery.consume(value, `c2l_recovery=${value}`, 'original'), /过期/);
  const stale = recovery.issue('original'); assert.throws(() => recovery.consume(stale, `c2l_recovery=${stale}`, 'changed'), /权限已变化/);
  const expired = recovery.issue('original'); now += 300001;
  assert.throws(() => recovery.consume(expired, `c2l_recovery=${expired}`, 'original'), /过期/);
  for (let i = 0; i < 32; i++) recovery.issue('original');
  assert.throws(() => recovery.issue('original'), /页面过多/);
});
test('only a top-level GET is exempted from cross-site rejection; OAuth return is pinned to the configured service', () => {
  const request = { method: 'GET', url: '/connect', headers: { 'sec-fetch-mode': 'navigate', 'sec-fetch-dest': 'document' } };
  assert.equal(recoveryNavigation(request), true);
  for (const input of [{ ...request, method: 'POST' }, { ...request, url: '/api/status' }, { ...request, headers: { 'sec-fetch-mode': 'cors' } }, { ...request, headers: { 'sec-fetch-mode': 'navigate', 'sec-fetch-dest': 'iframe' } }]) assert.equal(recoveryNavigation(input), false);
  assert.equal(authorizationReturn('https://relay.example/authorize?state=keep', 'https://relay.example'), 'https://relay.example/authorize?state=keep');
  for (const value of ['https://evil.example/authorize?state=bad', 'https://relay.example/link?state=bad', 'https://u:p@relay.example/authorize?state=bad', 'https://relay.example/authorize?state=bad#secret', 'https://relay.example/authorize', 'javascript:alert(1)']) assert.throws(() => authorizationReturn(value, 'https://relay.example'));
});
test('ordinary cloud pages contain no manual pairing field and show the requesting client without trusting its name', () => {
  const params = { ticket: secret(), client: { clientName: '<img src=x onerror=alert(1)>' }, authRequest: { scope: ['files:read','files:write'], redirectUri: 'https://client.example/callback' }, origin: 'https://relay.example', requestUrl: 'https://relay.example/authorize?state=keep' };
  const unbound = consentPage(params);
  assert.doesNotMatch(unbound, /name="pair"|type="password"|<form/);
  assert.match(unbound, /id="recover-device"/); assert.match(unbound, /127\.0\.0\.1:47631\/connect#return=/);
  assert.doesNotMatch(unbound, /<img src/); assert.match(unbound, /&lt;img src/);
  const bound = consentPage({ ...params, boundDevice: { deviceId: '1'.repeat(32), description: { name: 'PC' } } });
  assert.match(bound, /id="approve"[^>]*>允许读写并继续/);
  assert.doesNotMatch(bound, /name="pair"|id="recover-device"/);
  const readOnly = consentPage({ ...params, authRequest: { ...params.authRequest, scope: ['files:read'] }, boundDevice: { deviceId: '1'.repeat(32) } });
  assert.doesNotMatch(readOnly, /name="directWrite"/); assert.match(readOnly, /允许查看并继续/);
});

test('real browser: original OAuth page -> local confirmation -> browser binding -> same OAuth request, with no code entry', { timeout: 90000 }, async t => {
  const base = await fs.mkdtemp(path.join(os.tmpdir(), 'c2l-browser-recovery-'));
  const folder = path.join(base, 'sample'); await fs.mkdir(folder);
  const store = new Store(path.join(base, 'private'));
  const app = await startController({ port: 0, store, allowLocalRelay: true, networkOptions: { env: {}, systemProxy: async () => ({ proxy: '' }) }, openBrowser: async () => assert.fail('Recovery must navigate the same tab, not open a separate browser.') });
  const bundle = await build({ entryPoints: ['src/relay/worker.mjs'], bundle: true, write: false, format: 'esm', platform: 'neutral', mainFields: ['module', 'main'], external: ['cloudflare:workers'] });
  const enrollmentKey = secret();
  const mf = new Miniflare(convertV4MiniflareOptions({ modules: true, script: bundle.outputFiles[0].text, compatibilityDate: '2026-09-20', compatibilityFlags: ['nodejs_compat','global_fetch_strictly_public'], host: '127.0.0.1', port: 0, kvNamespaces: ['OAUTH_KV'], durableObjects: { DEVICES: { className: 'Device', useSQLite: true }, REGISTRY: { className: 'Registry', useSQLite: true } }, bindings: { ALLOW_LOOPBACK: 'true', ENROLLMENT_KEY: enrollmentKey, CUSTOM_CONNECTOR_ENABLED: 'true', MULTI_DEVICE: 'true', TEST_RECOVERY_ORIGIN: app.origin } }));
  const origin = (await mf.ready).origin;
  const local = (route, body, headers = {}) => fetch(`${app.origin}/api/${route}`, { method: body === undefined ? 'GET' : 'POST', headers: { 'X-Chat2Local-Token': app.token, Origin: app.origin, 'Content-Type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const post = (url, value, headers = {}) => fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(value), redirect: 'manual' });
  const root = await decode(await local('root/add', { path: folder, writeMode: 'direct', confirmDirect: true }));
  await decode(await local('enroll', { origin, enrollmentToken: enrollmentKey }));
  await until(() => app.bridge.state === 'connected');
  const before = await store.load();
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  t.after(async () => { await browser.close(); await app.close(); await mf.dispose(); await fs.rm(base, { recursive: true, force: true }); });
  const context = await browser.newContext(); const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const callback = 'http://127.0.0.1:54321/recovery-callback'; await page.route(`${callback}*`, route => route.fulfill({ status: 200, body: 'Synthetic OAuth callback' }));
  const client = await decode(await post(`${origin}/oauth/register`, { client_name: 'Recovery test client', redirect_uris: [callback], token_endpoint_auth_method: 'none', grant_types: ['authorization_code','refresh_token'], response_types: ['code'] }), 201);
  const verifier = secret(); const state = secret();
  const query = new URLSearchParams({ response_type: 'code', client_id: client.client_id, redirect_uri: callback, scope: 'files:read files:write', state, code_challenge_method: 'S256', code_challenge: createHash('sha256').update(verifier).digest('base64url'), resource: `${origin}/mcp` });
  const authUrl = `${origin}/authorize?${query}`;
  await page.goto(authUrl);
  assert.equal(await page.locator('input[name=pair]').count(), 0);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await fs.mkdir('.artifacts', { recursive: true }); await page.screenshot({ path: '.artifacts/compact-cloud-unbound.png', fullPage: true });
  await page.locator('#recover-device').click(); await page.waitForURL(`${app.origin}/connect`);
  assert.equal(await page.evaluate(() => sessionStorage.getItem('chat2local-control')), null);
  assert.equal(await page.locator('#recovery-continue').isEnabled(), true);
  const nonce = await page.locator('#recovery-token').inputValue(); assert.notEqual(nonce, app.token);
  const cookies = (await context.cookies(`${app.origin}/connect`)).map(c => `${c.name}=${c.value}`).join('; ');
  const command = { nonce, confirm: true, returnUrl: authUrl };
  assert.equal((await post(`${app.origin}/connect/continue`, command, { Origin: 'https://evil.example', Cookie: cookies })).status, 403);
  assert.equal((await post(`${app.origin}/connect/continue`, command, { Origin: app.origin })).status, 403);
  assert.equal((await post(`${app.origin}/connect/continue`, { ...command, returnUrl: 'https://evil.example/authorize?state=x' }, { Origin: app.origin, Cookie: cookies })).status, 400);
  assert.equal((await fetch(`${app.origin}/api/status`)).status, 401);
  await page.locator('#recovery-continue').click(); await page.waitForURL(`${origin}/link`);
  await page.locator('#continue:enabled').waitFor();
  assert.equal(new URL(page.url()).hash, '');
  assert.equal((await post(`${app.origin}/connect/continue`, command, { Origin: app.origin, Cookie: cookies })).status, 409);
  await page.locator('#continue').click(); await page.waitForURL(authUrl);
  await page.locator('#approve').waitFor({ state: 'visible' });
  assert.equal(new URL(page.url()).searchParams.get('state'), state);
  assert.equal(await page.locator('#approve').textContent(), '允许读写并继续');
  assert.equal(await page.locator('input[type=password]').count(), 0);
  assert.equal(await page.locator('details[open]').count(), 0);
  const unchanged = await store.load(); assert.deepEqual(unchanged.config, before.config); assert.deepEqual(unchanged.secrets, before.secrets);
  assert.deepEqual(await fs.readdir(folder), []);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.screenshot({ path: '.artifacts/compact-cloud-bound.png', fullPage: true });
  await page.locator('#approve').click(); await page.waitForURL(`${callback}*`);
  const returned = new URL(page.url()); assert.equal(returned.searchParams.get('state'), state);
  const tokens = await decode(await fetch(`${origin}/oauth/token`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', client_id: client.client_id, redirect_uri: callback, code: returned.searchParams.get('code'), code_verifier: verifier, resource: `${origin}/mcp` }) }));
  assert.ok(tokens.scope.split(' ').includes('files:write'));
  const result = (await decode(await post(`${origin}/mcp`, { jsonrpc: '2.0', id: 'write-once', method: 'tools/call', params: { name: 'write_file', arguments: { rootId: root.id, path: 'test.txt', content: 'After explicit browser consent', expectedHash: null } } }, { Authorization: `Bearer ${tokens.access_token}` }))).result;
  assert.equal(result.isError, false, result.content[0].text);
  assert.equal(await fs.readFile(path.join(folder, 'test.txt'), 'utf8'), 'After explicit browser consent');
  assert.deepEqual(errors, []);
});
