const escapeHtml = text => String(text).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const style = `*{box-sizing:border-box}body{font:16px/1.65 system-ui,-apple-system,Segoe UI,sans-serif;background:#f5f6f8;color:#1b2434;margin:0;padding:32px 18px}main{max-width:560px;margin:5vh auto;background:white;border:1px solid #e0e5ec;border-radius:18px;padding:28px}header{font-weight:700;color:#2155be;margin-bottom:22px}h1{font-size:26px;line-height:1.35;margin:0 0 16px}p{overflow-wrap:anywhere}button,.primary{font:inherit;display:block;background:#2155be;color:white;border:0;border-radius:8px;padding:13px 20px;width:100%;text-align:center;cursor:pointer;text-decoration:none;margin-top:22px}.device{background:#f1f5fc;border-radius:9px;padding:12px 15px;margin:12px 0}.muted,details{font-size:13px;color:#627187}details{margin-top:18px}summary{cursor:pointer}label{display:block;margin:10px 0}fieldset{border:0;padding:0;margin:0}small{overflow-wrap:anywhere}.waiting{color:#506078}[hidden]{display:none!important}@media(max-width:440px){main{padding:22px 18px;margin-top:2vh}h1{font-size:23px}}`;

/** Ordinary users never see or have to fill the legacy pairing-code form.
 * Backend legacy proof support stays intact for existing clients/diagnostics.
 */
export function consentPage({ ticket, client, authRequest, origin, boundDevice, boundDevices = [], requestUrl, recoveryOrigin = 'http://127.0.0.1:47631' }) {
  const scopes = authRequest.scope.length ? authRequest.scope : ['files:read', 'files:propose'];
  const write = scopes.includes('files:write');
  const deviceName = boundDevice?.description?.name || '已验证的电脑';
  const recovery = `${recoveryOrigin}/connect#return=${encodeURIComponent(requestUrl)}`;
  const details = `<details><summary>连接详情</summary><p>请求方：${escapeHtml(client.clientName || '未命名客户端')}</p><p>回调地址：${escapeHtml(authRequest.redirectUri)}</p><p>服务：${escapeHtml(origin)}</p></details>`;
  const heading = boundDevice ? (write ? '允许读写所选文件夹？' : '允许查看所选文件夹？') : '连接这台电脑';
  const body = !boundDevice
    ? `<p id="waiting-device" class="waiting" role="status">这次授权还没有识别到电脑。点击下面的按钮继续，原来的目录权限会保留。</p><input type="hidden" name="ticket" value="${escapeHtml(ticket)}"><a class="primary" id="recover-device" href="${escapeHtml(recovery)}">连接这台电脑</a><p class="muted">在这台电脑确认后自动回到这里，无需填写配对码。若本机程序未运行，请先打开 chat2local。</p>`
    : `<form action="/authorize" method="post"><input type="hidden" name="ticket" value="${escapeHtml(ticket)}"><input type="hidden" name="source" value="browser">${boundDevices.length > 1 ? '<fieldset><legend>本次连接的电脑</legend>' + boundDevices.map(item => `<label class="device"><input type="checkbox" name="device" value="${item.deviceId}" checked> ${escapeHtml(item.description?.name || '已验证电脑')} · ${escapeHtml(item.description?.system || '')}${item.online === false ? '（当前离线）' : ''}</label>`).join('') + '</fieldset>' : `<div class="device">${escapeHtml(deviceName)}</div>`}<p>范围：仅限本机已经授权的文件夹。</p><p>${write ? '允许读取、创建和修改文本；覆盖前自动备份。' : '允许读取文本，不修改文件。'}</p><p class="muted">不开放其他目录、不删除文件、不执行命令。文件内容会经过连接服务与 AI 平台。</p><button id="approve" type="submit">${write ? '允许读写并继续' : '允许查看并继续'}</button>${write || scopes.includes('files:propose') ? `<details><summary>其他权限选项</summary>${write ? '<label><input type="checkbox" name="directWrite" value="yes" checked> 允许直接读写（取消后仅查看）</label>' : ''}${scopes.includes('files:propose') ? '<label><input type="checkbox" name="propose" value="yes"> 允许提交需本机确认的修改建议</label>' : ''}</details>` : ''}</form>`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>chat2local · 连接授权</title><script defer src="/authorize-status.js"></script><style>${style}</style></head><body><main><header>chat2local</header><h1>${heading}</h1><p class="muted">请求应用：<strong>${escapeHtml(client.clientName || '未命名客户端')}</strong></p>${body}${details}</main></body></html>`;
}
